---
layout: page
title: reproducible research
tagline: for the R novice
description: reproducible research for the R beginner with RStudio, knitr
---

In technical work or research that utilizes a computer, the three common file types are 
data files, computer scripts to run the analysis, and presentation documents to report findings. This course is about explicitly linking the technical report, paper, or talk to the software, scripts, and data files that generated the findings. 

### planning

- Calendar
- Syllabus and policies

### materials

Week 1

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 

Week 2 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 

Week 3 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 

Week 4 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]  

Week 5 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]   

Week 6 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]   

Week 7 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]  

Week 8 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]  

Week 9 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]  

Week 10 

- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links] 
- Topic [assignments] [tutorials] [slides] [notes] [links]  

### 





