---
layout: page
title: getting started
tagline: agenda 
output: html_document 
---

```{r setup, include = FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
opts_chunk$set(include = FALSE, echo = FALSE, message = FALSE, warning = FALSE)
```

```{r lib}
library(readxl)
library(dplyr)
```

```{r agenda-functions}
# include set_path_for_runall in every Rmd script run from the 
# runall.R script if the goal is to knit(Rmd) to create the 
# md file correctly formatted for gh-pages 
set_path_for_runall <- function(proj_dir, file_dir) {
	if (exists('runall_obj')) { # does the object exist?
			file_dir <- paste0(proj_dir, '/', file_dir)
			} 
	file_dir <- file_dir
}
```

```{r set-file-path}
# required to run this Rmd from runall.R script
proj_dir <- 'creating-reproducible-reports'
file_dir <- 'data/agenda.xlsx'
file_dir <- set_path_for_runall(proj_dir, file_dir)
```

```{r create-agenda}
df <- read_excel(file_dir) %>% 
	mutate(space1 = NA, space2 = NA) %>%
  select(time, space1, activity, space2, format) %>%
	rename(' ' = space1, ' ' = space2)

sel1 <- df$activity == 'day 1'
sel2 <- df$activity == 'day 2'

idx1 <- which(df$activity %in% 'day 1')
idx2 <- which(df$activity %in% 'day 2')
n <- length(df$activity)

df1 <- df[(idx1 + 1):(idx2 - 1), ]
df2 <- df[(idx2 + 1):n, ]

df1[is.na(df1)] <- " "# replaces NAs with 2 blanks
df2[is.na(df2)] <- " " # replaces NAs with 2 blanks
```

### Session 1

To get the most out of the first session, do the pre-workshop homework before arriving. 

```{r agenda-1, include = TRUE}
kable(df1)
```

### Session 2

To get the most out of the second session, complete the sample report tutorial before the second session.  

```{r agenda-2, include = TRUE}
kable(df2)
```


--- 
Return to the [main page](../index.html) 

