---
title: "work summary"
tagline: "reproducible research for the R novice"
output:
  html_document:
    keep_md: yes
---

### week 0 

- Install software: R, RStudio, and Git 
- Create a GitHub account and make sure you can "talk" to it  
- **Due by the start of week 1** 

### weeks 1--2

- Create a new repo for Project 1: the calibration report 
- Follow the tutorials to recreate the example  
- Review your past technical work and find a suitable report to use as the subject of project 2  
- **Due by the start of week 3** 

### weeks 3--5

- Create a new repo for Project 2: based on the prior work you identified earlier 
- Recreate this prior work, but make it reproducible  
- Practice giving feedback on someone else's reproducible project 
- **Due by the start of week 6** 

### weeks 6--10

- Create a new repo for Project 3: the major term project 
- Give continuous feedback on someone else's reproducible project 
- Project attributes include file management, version control, literate programming, gathering data, data carpentry, analyzing data, creating tables and graphs, and reporting to present results.   
- **Due by the start of finals week** 

---

[back to main page](../index.html)










