---
layout: page
title: reproducible research
tagline: for the R novice
description: Introduces R, RStudio, and R Markdown as tools to create
             dynamically reproducible reports. For R novices. 
output: 
  html_document:
    keep_md: TRUE
---

We explore the principles and practices of reproducible research, from gathering data to analyzing data and presenting results. Students implement a  workflow that includes file management, version control, literate programming, data carpentry, creating tables and graphs, and reporting---all within the context of producing reproducible technical reports.






### week 0 

- [Syllabus](pages/cm001_syllabus.html) 
- [Work summary and due dates](pages/cm002_deadlines.html)


### week 1


### week 2 


### help  

- [Quick R website](http://www.statmethods.net/) by Robert Kabacoff, a big help for everyday R tasks. 
- [R Markdown](http://rmarkdown.rstudio.com/) by the folks at RStudio. 
- [knitr options](http://yihui.name/knitr/options/) by Yihui Xie, the author of knitr.  
- [R-bloggers](https://www.r-bloggers.com/) by Tal Galili, a searchable collection of blog posts by R bloggers everywhere. 
- [Stackoverflow](http://stackoverflow.com/questions/tagged/r), a searchable Q&A website for programming questions. 
- [Advanced R](http://adv-r.had.co.nz/) by Hadley Wickham, for when you really want to understand R. 
- [ggplot2 help](http://docs.ggplot2.org/current/index.html) by Hadley Wickham and Winston Chang, for all of the details. 

### books I recommend

- [*R in Action, 2/e*](https://www.manning.com/books/r-in-action-second-edition) by Robert Kabacoff, 2015, Manning Publications. If you want to buy just one good reference for R, this is the one I recommend. It covers R basics including statistical analysis and graphics. 
- [*R Graphics, 2/e*](https://www.crcpress.com/R-Graphics-Second-Edition/Murrell/p/book/9781439831762) by Paul Murrell, 2011, CRC Press. This is the book for learning about the four major R graphics systems (`base, grid, lattice, ggplot2`).  The author's [book website](https://www.stat.auckland.ac.nz/~paul/RG2e/) has the code for every figure in the book. 



